paypal_api:
  ipn_url: 'https://ipnpb.sandbox.paypal.com/cgi-bin/webscr?cmd=_notify-validate'
line_pay_api:
  end_point: 'https://sandbox-api-pay.line.me'
paypay_url: 'https://paypay-webpayment-stg.herokuapp.com'
